export * from './getGeneration'
export * from './getHighestStat'
export * from './getEvolutionStage'
export * from './getAllPokemonNames'
export * from './getPokemonImage'
export * from './getPokemon'
export * from './comparatePokemons'
export * from './getBgColor'